/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./src/**/*.{js,ts,jsx,tsx}", "./src/**/*.stories.{js,ts,jsx,tsx}"],
  theme: {
  	extend: {
  		colors: {
  			'kpds-orange-900': 'var(--color-orange-900)',
  			'kpds-orange-100': 'var(--color-orange-100)',
  			'kpds-red-900': 'var(--color-red-900)',
  			'kpds-red-100': 'var(--color-red-100)',
  			'kpds-green-900': 'var(--color-green-900)',
  			'kpds-green-100': 'var(--color-green-100)',
  			'kpds-white': 'var(--color-white)',
  			'kpds-black': 'var(--color-black)',
  			'kpds-black-950': 'var(--color-black-950)',
  			'kpds-black-900': 'var(--color-black-900)',
  			'kpds-black-alpha-200': 'var(--color-black-alpha-200)',
  			'kpds-black-alpha-100': 'var(--color-black-alpha-100)',
  			'kpds-black-alpha-50': 'var(--color-black-alpha-50)',
  			'kpds-white-0': 'var(--color-white-0)',
  			'kpds-white-alpha-200': 'var(--color-white-alpha-200)',
  			'kpds-white-alpha-100': 'var(--color-white-alpha-100)',
  			'kpds-white-alpha-50': 'var(--color-white-alpha-50)',
  			'kpds-gray-50': 'var(--color-gray-50)',
  			'kpds-gray-100': 'var(--color-gray-100)',
  			'kpds-gray-200': 'var(--color-gray-200)',
  			'kpds-gray-300': 'var(--color-gray-300)',
  			'kpds-gray-400': 'var(--color-gray-400)',
  			'kpds-gray-500': 'var(--color-gray-500)',
  			'kpds-gray-600': 'var(--color-gray-600)',
  			'kpds-gray-700': 'var(--color-gray-700)',
  			'kpds-gray-800': 'var(--color-gray-800)',
  			'kpds-gray-850': 'var(--color-gray-850)',
  			'kpds-gray-900': 'var(--color-gray-900)',
  			'kpds-gray-950': 'var(--color-gray-950)',
  			'kpds-purple-50': 'var(--color-purple-50)',
  			'kpds-purple-100': 'var(--color-purple-100)',
  			'kpds-purple-200': 'var(--color-purple-200)',
  			'kpds-purple-300': 'var(--color-purple-300)',
  			'kpds-purple-400': 'var(--color-purple-400)',
  			'kpds-purple-500': 'var(--color-purple-500)',
  			'kpds-purple-600': 'var(--color-purple-600)',
  			'kpds-purple-700': 'var(--color-purple-700)',
  			'kpds-purple-800': 'var(--color-purple-800)',
  			'kpds-purple-850': 'var(--color-purple-850)',
  			'kpds-purple-950': 'var(--color-purple-950)',
  			'kpds-purple-900': 'var(--color-purple-900)',
  			'kpds-orange-50': 'var(--color-orange-50)',
  			'kpds-orange-200': 'var(--color-orange-200)',
  			'kpds-orange-300': 'var(--color-orange-300)',
  			'kpds-orange-400': 'var(--color-orange-400)',
  			'kpds-orange-500': 'var(--color-orange-500)',
  			'kpds-orange-600': 'var(--color-orange-600)',
  			'kpds-orange-700': 'var(--color-orange-700)',
  			'kpds-orange-800': 'var(--color-orange-800)',
  			'kpds-orange-850': 'var(--color-orange-850)',
  			'kpds-orange-950': 'var(--color-orange-950)',
  			'kpds-red-50': 'var(--color-red-50)',
  			'kpds-red-200': 'var(--color-red-200)',
  			'kpds-red-300': 'var(--color-red-300)',
  			'kpds-red-400': 'var(--color-red-400)',
  			'kpds-red-500': 'var(--color-red-500)',
  			'kpds-red-600': 'var(--color-red-600)',
  			'kpds-red-700': 'var(--color-red-700)',
  			'kpds-red-800': 'var(--color-red-800)',
  			'kpds-red-850': 'var(--color-red-850)',
  			'kpds-red-950': 'var(--color-red-950)',
  			'kpds-green-50': 'var(--color-green-50)',
  			'kpds-green-200': 'var(--color-green-200)',
  			'kpds-green-300': 'var(--color-green-300)',
  			'kpds-green-400': 'var(--color-green-400)',
  			'kpds-green-500': 'var(--color-green-500)',
  			'kpds-green-600': 'var(--color-green-600)',
  			'kpds-green-700': 'var(--color-green-700)',
  			'kpds-green-800': 'var(--color-green-800)',
  			'kpds-green-850': 'var(--color-green-850)',
  			'kpds-green-950': 'var(--color-green-950)',
  			'kpds-mint-50': 'var(--color-mint-50)',
  			'kpds-mint-100': 'var(--color-mint-100)',
  			'kpds-mint-200': 'var(--color-mint-200)',
  			'kpds-mint-300': 'var(--color-mint-300)',
  			'kpds-mint-400': 'var(--color-mint-400)',
  			'kpds-mint-500': 'var(--color-mint-500)',
  			'kpds-mint-600': 'var(--color-mint-600)',
  			'kpds-mint-700': 'var(--color-mint-700)',
  			'kpds-mint-800': 'var(--color-mint-800)',
  			'kpds-mint-850': 'var(--color-mint-850)',
  			'kpds-mint-900': 'var(--color-mint-900)',
  			'kpds-mint-950': 'var(--color-mint-950)',
  			'kpds-blue-50': 'var(--color-blue-50)',
  			'kpds-blue-100': 'var(--color-blue-100)',
  			'kpds-blue-200': 'var(--color-blue-200)',
  			'kpds-blue-300': 'var(--color-blue-300)',
  			'kpds-blue-400': 'var(--color-blue-400)',
  			'kpds-blue-500': 'var(--color-blue-500)',
  			'kpds-blue-600': 'var(--color-blue-600)',
  			'kpds-blue-700': 'var(--color-blue-700)',
  			'kpds-blue-800': 'var(--color-blue-800)',
  			'kpds-blue-850': 'var(--color-blue-850)',
  			'kpds-blue-900': 'var(--color-blue-900)',
  			'kpds-blue-950': 'var(--color-blue-950)',
  			'kpds-yellow-50': 'var(--color-yellow-50)',
  			'kpds-yellow-100': 'var(--color-yellow-100)',
  			'kpds-yellow-200': 'var(--color-yellow-200)',
  			'kpds-yellow-300': 'var(--color-yellow-300)',
  			'kpds-yellow-400': 'var(--color-yellow-400)',
  			'kpds-yellow-500': 'var(--color-yellow-500)',
  			'kpds-yellow-600': 'var(--color-yellow-600)',
  			'kpds-yellow-700': 'var(--color-yellow-700)',
  			'kpds-yellow-800': 'var(--color-yellow-800)',
  			'kpds-yellow-850': 'var(--color-yellow-850)',
  			'kpds-yellow-900': 'var(--color-yellow-900)',
  			'kpds-yellow-950': 'var(--color-yellow-950)',
  			'kpds-brown-50': 'var(--color-brown-50)',
  			'kpds-brown-100': 'var(--color-brown-100)',
  			'kpds-brown-200': 'var(--color-brown-200)',
  			'kpds-brown-300': 'var(--color-brown-300)',
  			'kpds-brown-400': 'var(--color-brown-400)',
  			'kpds-brown-500': 'var(--color-brown-500)',
  			'kpds-brown-600': 'var(--color-brown-600)',
  			'kpds-brown-700': 'var(--color-brown-700)',
  			'kpds-brown-800': 'var(--color-brown-800)',
  			'kpds-brown-850': 'var(--color-brown-850)',
  			'kpds-brown-900': 'var(--color-brown-900)',
  			'kpds-brown-950': 'var(--color-brown-950)',
  			background: 'var(--color-gray-50)',
  			foreground: 'var(--color-gray-950)'
  		},
  		borderRadius: {
  			'kpds-4': 'var(--radius-4)',
  			'kpds-6': 'var(--radius-6)',
  			'kpds-8': 'var(--radius-8)',
  			'kpds-10': 'var(--radius-10)',
  			'kpds-12': 'var(--radius-12)',
  			'kpds-16': 'var(--radius-16)',
  			'kpds-24': 'var(--radius-24)',
  			'kpds-28': 'var(--radius-28)'
  		},
  		fontSize: {
  			'kpds-10': 'var(--font-size-10)',
  			'kpds-12': 'var(--font-size-12)',
  			'kpds-13': 'var(--font-size-13)',
  			'kpds-14': 'var(--font-size-14)',
  			'kpds-16': 'var(--font-size-16)',
  			'kpds-18': 'var(--font-size-18)',
  			'kpds-20': 'var(--font-size-20)',
  			'kpds-24': 'var(--font-size-24)',
  			'kpds-28': 'var(--font-size-28)',
  			'kpds-36': 'var(--font-size-36)',
  			'kpds-64': 'var(--font-size-64)'
  		},
  		fontWeight: {
  			'kpds-regular': 'var(--font-weight-regular)',
  			'kpds-semibold': 'var(--font-weight-semibold)',
  			'kpds-bold': 'var(--font-weight-bold)'
  		},
  		lineHeight: {
  			'kpds-14': 'var(--line-height-14)',
  			'kpds-16': 'var(--line-height-16)',
  			'kpds-18': 'var(--line-height-18)',
  			'kpds-20': 'var(--line-height-20)',
  			'kpds-22': 'var(--line-height-22)',
  			'kpds-26': 'var(--line-height-26)',
  			'kpds-28': 'var(--line-height-28)',
  			'kpds-32': 'var(--line-height-32)',
  			'kpds-36': 'var(--line-height-36)',
  			'kpds-44': 'var(--line-height-44)',
  			'kpds-72': 'var(--line-height-72)'
  		},
  		spacing: {
  			'kpds-0': 'var(--spacing-0)',
  			'kpds-1': 'var(--spacing-1)',
  			'kpds-2': 'var(--spacing-2)',
  			'kpds-4': 'var(--spacing-4)',
  			'kpds-6': 'var(--spacing-6)',
  			'kpds-8': 'var(--spacing-8)',
  			'kpds-10': 'var(--spacing-10)',
  			'kpds-12': 'var(--spacing-12)',
  			'kpds-16': 'var(--spacing-16)',
  			'kpds-18': 'var(--spacing-18)',
  			'kpds-20': 'var(--spacing-20)',
  			'kpds-24': 'var(--spacing-24)',
  			'kpds-32': 'var(--spacing-32)',
  			'kpds-38': 'var(--spacing-38)',
  			'kpds-40': 'var(--spacing-40)',
  			'kpds-48': 'var(--spacing-48)',
  			'kpds-56': 'var(--spacing-56)',
  			'kpds-64': 'var(--spacing-64)',
  			'kpds-80': 'var(--spacing-80)',
  			'kpds-96': 'var(--spacing-96)',
  			'kpds-160': 'var(--spacing-160)'
  		},
  		keyframes: {
  			'accordion-down': {
  				from: {
  					height: '0'
  				},
  				to: {
  					height: 'var(--radix-accordion-content-height)'
  				}
  			},
  			'accordion-up': {
  				from: {
  					height: 'var(--radix-accordion-content-height)'
  				},
  				to: {
  					height: '0'
  				}
  			}
  		},
  		animation: {
  			'accordion-down': 'accordion-down 0.2s ease-out',
  			'accordion-up': 'accordion-up 0.2s ease-out'
  		}
  	}
  },
  plugins: [require("tailwindcss-animate")],
};
